# -*- coding: utf-8 -*-
"""
/***************************************************************************
 AdvancedRBFInterpolation
                                 A QGIS plugin
 Advanced RBF interpolation with neighborhood control, local interpolation, and extrapolation options for large datasets
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-06-16
        copyright            : (C) 2025 by Delano M. Santos
        email                : projetos.delano@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Delano M. Santos'
__date__ = '2025-06-16'
__copyright__ = '(C) 2025 by Delano M. Santos'

import os
from qgis.PyQt.QtCore import QCoreApplication, QTranslator, QSettings


def init_locale():
    """Initialize translations for the plugin."""
    locale = QSettings().value('locale/userLocale')[0:2]
    locale_path = os.path.join(os.path.dirname(__file__), 'i18n', f'{locale}.qm')
    if os.path.exists(locale_path):
        translator = QTranslator()
        translator.load(locale_path)
        QCoreApplication.installTranslator(translator)


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load AdvancedRBFInterpolation class from file AdvancedRBFInterpolation.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    # Initialize translations
    init_locale()
    
    from .advanced_rbf_interpolation import AdvancedRBFInterpolationPlugin
    return AdvancedRBFInterpolationPlugin()
